# Generated by Django 5.0.6 on 2026-03-31 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('interesse', models.CharField(choices=[('comprar', 'Comprar imóvel'), ('vender', 'Vender imóvel'), ('investir', 'Investir'), ('visita', 'Agendar visita'), ('outro', 'Outro')], default='comprar', max_length=20, verbose_name='Interesse')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em contato'), ('negociando', 'Negociando'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=20, verbose_name='Status')),
                ('anotacoes', models.TextField(blank=True, verbose_name='Anotações internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='imoveis.imovel', verbose_name='Imóvel de interesse')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
            },
        ),
    ]
