# Generated by Django 5.0.6 on 2026-04-07 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='interesse',
        ),
        migrations.AddField(
            model_name='lead',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Corretor responsável'),
        ),
        migrations.AddField(
            model_name='lead',
            name='distribuido_automaticamente',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='operacao',
            field=models.CharField(choices=[('venda', 'Comprar imóvel'), ('locacao', 'Alugar imóvel'), ('lancamento', 'Lançamento'), ('investir', 'Investir'), ('vender', 'Vender meu imóvel'), ('outro', 'Outro')], default='venda', max_length=20, verbose_name='Tipo de operação'),
        ),
        migrations.AddField(
            model_name='lead',
            name='perfil_cliente',
            field=models.CharField(blank=True, choices=[('', 'Não identificado'), ('comprador', 'Comprador'), ('investidor', 'Investidor'), ('empresa', 'Empresa (B2B)'), ('locatario', 'Locatário')], max_length=20, verbose_name='Perfil do cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='regiao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Região de interesse'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ticket_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ticket estimado (R$)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tipo_imovel',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('residencial', 'Residencial'), ('comercial', 'Comercial'), ('rural', 'Rural'), ('condominio', 'Condomínio')], max_length=20, verbose_name='Tipo do imóvel'),
        ),
    ]
