# Generated by Django 5.0.6 on 2026-04-07 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('lancamentos', 'Lançamentos'), ('revenda', 'Revenda (Venda Pronta)'), ('locacao', 'Locação'), ('alto_padrao', 'Alto Padrão'), ('comercial', 'Comercial B2B'), ('investidor', 'Investidor')], max_length=20, unique=True, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cor', models.CharField(default='#b8974a', max_length=7, verbose_name='Cor (hex)')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraRoteamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da regra')),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Menor número = maior prioridade', verbose_name='Prioridade')),
                ('operacao', models.CharField(blank=True, choices=[('', 'Qualquer'), ('venda', 'Venda'), ('locacao', 'Locação'), ('lancamento', 'Lançamento')], max_length=20, verbose_name='Tipo de operação')),
                ('tipo_imovel', models.CharField(blank=True, choices=[('', 'Qualquer'), ('residencial', 'Residencial'), ('comercial', 'Comercial'), ('rural', 'Rural'), ('condominio', 'Condomínio')], max_length=20, verbose_name='Tipo do imóvel')),
                ('perfil_cliente', models.CharField(blank=True, choices=[('', 'Qualquer'), ('comprador', 'Comprador'), ('investidor', 'Investidor'), ('empresa', 'Empresa (B2B)'), ('locatario', 'Locatário')], max_length=20, verbose_name='Perfil do cliente')),
                ('ticket_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ticket mínimo (R$)')),
                ('ticket_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ticket máximo (R$)')),
                ('regiao', models.CharField(blank=True, max_length=100, verbose_name='Região / Cidade')),
                ('ativa', models.BooleanField(default=True, verbose_name='Regra ativa')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='core.time', verbose_name='Time destino')),
            ],
            options={
                'verbose_name': 'Regra de Roteamento',
                'verbose_name_plural': 'Regras de Roteamento',
                'ordering': ['prioridade'],
            },
        ),
        migrations.CreateModel(
            name='PerfilCorretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creci', models.CharField(blank=True, max_length=20, verbose_name='CRECI')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='corretores/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo (recebe leads)')),
                ('posicao_fila', models.PositiveIntegerField(default=0, verbose_name='Posição na fila')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('total_leads_recebidos', models.PositiveIntegerField(default=0, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corretores', to='core.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Perfil do Corretor',
                'verbose_name_plural': 'Perfis dos Corretores',
                'ordering': ['posicao_fila', 'user__first_name'],
            },
        ),
    ]
