# Generated by Django 5.0.6 on 2026-03-31 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(default='SP', max_length=2)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='imoveis.cidade')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tipo', models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('cobertura', 'Cobertura'), ('terreno', 'Terreno'), ('comercial', 'Comercial')], default='apartamento', max_length=20)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('vendido', 'Vendido'), ('alugado', 'Alugado'), ('reservado', 'Reservado')], default='disponivel', max_length=20)),
                ('destaque', models.CharField(blank=True, choices=[('', 'Nenhum'), ('destaque', 'Destaque'), ('novo', 'Novo'), ('oportunidade', 'Oportunidade'), ('exclusivo', 'Exclusivo')], max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Preço (R$)')),
                ('preco_negociavel', models.BooleanField(default=False, verbose_name='Preço negociável')),
                ('condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Condomínio (R$)')),
                ('iptu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IPTU mensal (R$)')),
                ('area_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Área total (m²)')),
                ('area_construida', models.PositiveIntegerField(blank=True, null=True, verbose_name='Área construída (m²)')),
                ('quartos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quartos')),
                ('suites', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Suítes')),
                ('banheiros', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Banheiros')),
                ('vagas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vagas de garagem')),
                ('andar', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Andar')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('diferenciais', models.TextField(blank=True, help_text='Digite cada diferencial em uma linha separada', verbose_name='Diferenciais (um por linha)')),
                ('meta_descricao', models.CharField(blank=True, max_length=160, verbose_name='Meta descrição (SEO)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo (visível no site)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False)),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cidade')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/', verbose_name='Foto')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('principal', models.BooleanField(default=False, verbose_name='Foto principal')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-principal', 'ordem'],
            },
        ),
    ]
