# Generated by Django 5.0.6 on 2026-04-07 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('tipo', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, verbose_name='CPF / CNPJ')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('telefone2', models.CharField(blank=True, max_length=20, verbose_name='Telefone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis', to='imoveis.proprietario', verbose_name='Proprietário'),
        ),
    ]
