# Generated by Django 5.0.6 on 2026-04-28 18:09

import django.db.models.deletion
import imoveis.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_proprietario_imovel_proprietario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='DocumentoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('matricula', 'Matrícula'), ('iptu', 'IPTU'), ('condominio', 'Boleto Condomínio'), ('contrato', 'Contrato'), ('planta', 'Planta do Imóvel'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do documento')),
                ('arquivo', models.FileField(upload_to=imoveis.models.documento_upload_path, verbose_name='Arquivo')),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['tipo', '-criado_em'],
            },
        ),
    ]
