# Generated by Django 5.0.6 on 2026-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_codigo_documentoimovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='Código'),
        ),
    ]
