# Generated by Django 5.0.6 on 2026-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_codigo_documentoimovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='condominio_fechado',
            field=models.BooleanField(default=False, verbose_name='Condomínio fechado'),
        ),
    ]
